export const FETCH_ANIME_DATA = "FETCH_ANIME_DATA";
export const FETCH_ANIME_DATA_START = "FETCH_ANIME_DATA_START";
export const FETCH_ANIME_DATA_SUCCESS = "FETCH_ANIME_DATA_SUCCESS";
export const FETCH_ANIME_DATA_FAILED = "FETCH_ANIME_DATA_FAILED";

export const FETCH_INFO_DATA = "FETCH_INFO_DATA";
export const FETCH_INFO_DATA_START = "FETCH_INFO_DATA_START";
export const FETCH_INFO_DATA_SUCCESS = "FETCH_INFO_DATA_SUCCESS";
export const FETCH_INFO_DATA_FAILED = "FETCH_INFO_DATA_FAILED";

export const CLEAR_VIDEO_DATA = "CLEAR_VIDEO_DATA";
export const FETCH_VIDEO_DATA = "FETCH_VIDEO_DATA";
export const FETCH_VIDEO_DATA_START = "FETCH_VIDEO_DATA_START";
export const FETCH_VIDEO_DATA_SUCCESS = "FETCH_VIDEO_DATA_SUCCESS";
export const FETCH_VIDEO_DATA_FAILED = "FETCH_VIDEO_DATA_FAILED";
export const CHANGE_STREAM_URL = "CHANGE_STREAM_URL";

export const TO_ZAWGYI = "TO_ZAWGYI";
